### ISSUE TITLE
How to use RotateAbout(rad, x, y) only for a specific object?

### ISSUE THREAD

**Issue by tagaism** [h8gi/canvas#5]
I have a very basic question.
When I use RotateAbout(rad, x, y) to one object all objects start to rotate around x, y point.
How to use RotateAbout only for a specific object?
I believe I must use Push() and Pop() function to preserve and to retrieve the context state.
But it doesn't seem to be worked and I can't figure out how to do that.

**Comment by h8gi** [comment]
Hello, tagaism!
I wrote simple example using RotateAbout(), Push() and Pop().
Since Push and Pop are derived from [gg](https://github.com/fogleman/gg) package, You can find more information in [gg examples](https://github.com/fogleman/gg/tree/master/examples).

https://github.com/h8gi/canvas/blob/a6361a06ab49a6fcc89eb649a46a6826460a6592/examples/rotate-objects/main.go#L1-L44

**Comment by tagaism** [comment]
@h8gi wow!
Thank you very much, your example helped a lot.
